import * as XLSX from 'xlsx';
import { saveAs } from 'file-saver';
import { Parcel } from '../services/wmsApi';

interface ParcelFilterState {
  search: string;
  status: string;
  destination: string;
  paymentMethod: string;
  dateRange: { from: string; to: string };
  sender: string;
  receiver: string;
  clerk: string;
}

interface ExportOptions {
  title?: string;
  filename?: string;
  includeFilters?: boolean;
  filterSummary?: string;
}

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric'
  });
};

const formatCurrency = (amount: number) => {
  return new Intl.NumberFormat('en-KE', {
    style: 'currency',
    currency: 'KES',
    minimumFractionDigits: 0
  }).format(amount).replace('KES', 'KSh');
};

const getStatusLabel = (status: number) => {
  const statusMap = {
    0: 'Pending',
    1: 'Confirmed',
    2: 'In Transit',
    3: 'Delivered',
    4: 'Cancelled'
  };
  return statusMap[status as keyof typeof statusMap] || 'Unknown';
};

const prepareExportData = (parcels: Parcel[]) => {
  return parcels.map(parcel => ({
    'Waybill Number': parcel.waybillNumber,
    'Status': getStatusLabel(parcel.status),
    'Destination': parcel.destination,
    'Sender': parcel.sender,
    'Sender Phone': parcel.senderTelephone,
    'Receiver': parcel.receiver,
    'Receiver Phone': parcel.receiverTelephone,
    'Amount': formatCurrency(parcel.totalAmount),
    'Quantity': parcel.quantity,
    'Payment Method': parcel.paymentMethods,
    'Description': parcel.description || 'N/A',
    'Created By': parcel.createdBy?.username || 'N/A',
    'Created Date': formatDate(parcel.createdAt),
    'Dispatched Date': parcel.dispatchedAt ? formatDate(parcel.dispatchedAt) : 'N/A'
  }));
};

const generateCSVContent = (data: any[]) => {
  if (data.length === 0) return '';
  
  const headers = Object.keys(data[0]);
  const csvRows = [
    headers.join(','), // Header row
    ...data.map(row => 
      headers.map(header => {
        const value = row[header];
        // Escape commas and quotes in CSV
        const escaped = String(value).replace(/"/g, '""');
        return `"${escaped}"`;
      }).join(',')
    )
  ];
  
  return csvRows.join('\n');
};

export const exportParcelsToCSV = (
  parcels: Parcel[],
  options: ExportOptions = {}
) => {
  const {
    filename = `parcels-export-${new Date().toISOString().split('T')[0]}.csv`,
    title = 'Parcels Export Report',
    includeFilters = false,
    filterSummary = ''
  } = options;

  const data = prepareExportData(parcels);
  let csvContent = '';

  // Add title and metadata
  if (includeFilters && filterSummary) {
    csvContent += `"${title}"\n`;
    csvContent += `"Export Date: ${new Date().toLocaleString()}"\n`;
    csvContent += `"Total Records: ${parcels.length}"\n`;
    csvContent += `"Filter Summary: ${filterSummary}"\n`;
    csvContent += '\n'; // Empty line before data
  }

  csvContent += generateCSVContent(data);

  // Create and download blob
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  saveAs(blob, filename);
};

export const exportParcelsToXLSX = (
  parcels: Parcel[],
  options: ExportOptions = {}
) => {
  const {
    filename = `parcels-export-${new Date().toISOString().split('T')[0]}.xlsx`,
    title = 'Parcels Export Report',
    includeFilters = false,
    filterSummary = ''
  } = options;

  const data = prepareExportData(parcels);
  
  // Create workbook
  const wb = XLSX.utils.book_new();
  
  // Create main data worksheet
  const ws = XLSX.utils.json_to_sheet(data);

  // Set column widths for better readability
  const colWidths = [
    { wch: 15 }, // Waybill Number
    { wch: 12 }, // Status
    { wch: 15 }, // Destination
    { wch: 20 }, // Sender
    { wch: 15 }, // Sender Phone
    { wch: 20 }, // Receiver
    { wch: 15 }, // Receiver Phone
    { wch: 12 }, // Amount
    { wch: 10 }, // Quantity
    { wch: 15 }, // Payment Method
    { wch: 25 }, // Description
    { wch: 15 }, // Created By
    { wch: 15 }, // Created Date
    { wch: 15 }  // Dispatched Date
  ];
  ws['!cols'] = colWidths;

  // Add the worksheet to workbook
  XLSX.utils.book_append_sheet(wb, ws, 'Parcels');

  // Create summary worksheet if filters are included
  if (includeFilters && filterSummary) {
    const summaryData = [
      { 'Report Information': 'Value' },
      { 'Report Information': title, 'Value': '' },
      { 'Report Information': 'Export Date', 'Value': new Date().toLocaleString() },
      { 'Report Information': 'Total Records', 'Value': parcels.length },
      { 'Report Information': 'Filter Summary', 'Value': filterSummary },
      { 'Report Information': '', 'Value': '' },
      { 'Report Information': 'Generated by', 'Value': 'NID Logistics WMS' }
    ];

    const summaryWs = XLSX.utils.json_to_sheet(summaryData);
    summaryWs['!cols'] = [{ wch: 20 }, { wch: 50 }];
    XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary');
  }

  // Write and download the file
  XLSX.writeFile(wb, filename);
};

export const generateFilterSummary = (filters: Partial<ParcelFilterState>) => {
  const activeSummary: string[] = [];
  
  if (filters.search) {
    activeSummary.push(`Search: "${filters.search}"`);
  }
  
  if (filters.status) {
    activeSummary.push(`Status: ${getStatusLabel(parseInt(filters.status))}`);
  }
  
  if (filters.destination) {
    activeSummary.push(`Destination: ${filters.destination}`);
  }
  
  if (filters.paymentMethod) {
    activeSummary.push(`Payment: ${filters.paymentMethod}`);
  }
  
  if (filters.dateRange?.from || filters.dateRange?.to) {
    const from = filters.dateRange.from || 'Start';
    const to = filters.dateRange.to || 'End';
    activeSummary.push(`Date Range: ${from} to ${to}`);
  }
  
  if (filters.sender) {
    activeSummary.push(`Sender: ${filters.sender}`);
  }
  
  if (filters.receiver) {
    activeSummary.push(`Receiver: ${filters.receiver}`);
  }
  
  if (filters.clerk) {
    activeSummary.push(`Clerk: ${filters.clerk}`);
  }
  
  return activeSummary.length > 0 
    ? activeSummary.join(', ')
    : 'No filters applied';
};